Feature/feature/get chain info for showing native token symbol
gnosis/safe-react-apps pull request #215
Opened 2021-11-25 14:34 UTC by yagopv

## What it solves
Resolves #185 

## How this PR fixes it
We are going to get the chain info using the SDK (https://github.com/gnosis/safe-apps-sdk/pull/258)

With the new info we are going to show the correct native token symbol

## How to test it
1) Open Tx-builder
2) Add a contract 
3) Check the labels showing the native token are showing the native one and not always ETH

2021-11-25 17:18 UTC, dasanra requested changes
We still have hardcoded references to ETH in this lines

https://github.com/gnosis/safe-react-apps/blob/8ecefdebe105be6039125be37d722f11668d3cc1/apps/tx-builder/src/components/Builder.tsx#L176

https://github.com/gnosis/safe-react-apps/blob/8ecefdebe105be6039125be37d722f11668d3cc1/apps/tx-builder/src/components/Builder.tsx#L211

Could you check it?

2021-11-25 17:42 UTC, yagopv commented
😱 I had the search filter in vscode with the drain-safe folder 😁

2021-11-26 10:29 UTC, DaniSomoza approved these changes
Approved! :D

2021-11-26 13:50 UTC, dasanra approved these changes

2021-11-26 13:52 UTC, merged